
;;; How many distinct terms are in the sequence generated by a^(b) for
;;; 2 <= a <= 100 and 2 <= b <= 100?

(in-package #:pe)

(defun euler-029 ()
  (loop with terms = nil
        for a from 2 to 100
        do (loop for b from 2 to 100
		 do (pushnew (expt a b) terms))
        finally (return (length terms))))

; (time (euler-029))
